### ISSUE TITLE
Could provide a detailed preprocessing, training, testing documentation?

### ISSUE THREAD

**Issue by youngstu** [stonyhu/DanceRevolution#3] opened 2020-09-14 11:26 UTC

**Comment by youngstu** [comment] 2020-09-14 11:27
Could provide a detailed preprocessing, training, testing documentation?

**Comment by wtnan2003** [comment] 2020-10-29 08:49
@youngstu Hi, Have you figure out how to train the model?

**Comment by stonyhu** [comment] 2020-12-07 08:00
Duplicate of #1

**Closed** 2020-12-18 02:03 UTC
